// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BackTop: typeof import('./src/components/backTop/index.vue')['default']
    BaseEmpty: typeof import('./src/components/baseEmpty/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    'Index copy': typeof import('./src/components/selectGame/index copy.vue')['default']
    Index_old: typeof import('./src/components/selectGame/index_old.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    NavLinks: typeof import('./src/components/navLinks/index.vue')['default']
    NavLogo: typeof import('./src/components/navLogo/index.vue')['default']
    NavPhDrawer: typeof import('./src/components/navPhDrawer/index.vue')['default']
    OpenIcon: typeof import('./src/components/navPhDrawer/openIcon.vue')['default']
    ScriptCard: typeof import('./src/components/scriptCard/index.vue')['default']
    SelectGame: typeof import('./src/components/selectGame/index.vue')['default']
    ThemeButton: typeof import('./src/components/themeButton/index.vue')['default']
    ThemeDialog: typeof import('./src/components/themeDialog/index.vue')['default']
    ThemeRadioGroup: typeof import('./src/components/themeRadioGroup/index.vue')['default']
    ThemeTable: typeof import('./src/components/themeTable/index.vue')['default']
    UploadIcon: typeof import('./src/components/uploadIcon/index.vue')['default']
    UploadImage: typeof import('./src/components/uploadImage/index.vue')['default']
  }
}

export { }
